DROP TABLE IF EXISTS EMPRUNT;
DROP TABLE IF EXISTS EXEMPLAIRE;
DROP TABLE IF EXISTS OEUVRE;
DROP TABLE IF EXISTS AUTEUR;
DROP TABLE IF EXISTS ADHERENT;

CREATE TABLE IF NOT EXISTS ADHERENT(
	idAdherent INT AUTO_INCREMENT,
	nomAdherent VARCHAR(50),
	adresse VARCHAR(50),
	datePaiement DATE,
	PRIMARY KEY(idAdherent)
)ENGINE=InnoDB	 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS AUTEUR(
	idAuteur INT AUTO_INCREMENT,
	nomAuteur VARCHAR(50),
	prenomAuteur VARCHAR(50),
	PRIMARY KEY(idAuteur)
)ENGINE=InnoDB	 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS OEUVRE(
	noOeuvre INT AUTO_INCREMENT,
	titre VARCHAR(50),
	dateParution DATE,
	idAuteur INT,
	PRIMARY KEY(noOeuvre),
	CONSTRAINT fk_oeuvre_auteur
		FOREIGN KEY (idAuteur) 
		REFERENCES AUTEUR(idAuteur)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=InnoDB	 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS EXEMPLAIRE(
	noExemplaire INT AUTO_INCREMENT,
	etat ENUM('neuf','bon','moyen','mauvais'),
	dateAchat DATE, 
	prix NUMERIC(5,2),
	noOeuvre INT,
	PRIMARY KEY (noExemplaire),
	CONSTRAINT fk_exemplaire_oeuvre
		FOREIGN KEY (noOeuvre)
		REFERENCES OEUVRE(noOeuvre)
		ON DELETE CASCADE
		ON UPDATE CASCADE
)ENGINE=InnoDB	 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS EMPRUNT(
	idAdherent INT, 
	noExemplaire INT,
	dateEmprunt DATE,
	dateRendu DATE,
	PRIMARY KEY (idAdherent, noExemplaire, dateEmprunt),
	CONSTRAINT fk_emprunt_adherent
		FOREIGN KEY (idAdherent)
		REFERENCES ADHERENT(idAdherent) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE 
		,
	CONSTRAINT fk_emprunt_exemplaire
		FOREIGN KEY (noExemplaire)
		REFERENCES EXEMPLAIRE(noExemplaire)
		ON DELETE CASCADE 
		ON UPDATE CASCADE 

)ENGINE=InnoDB	 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_general_ci;

LOAD DATA LOCAL INFILE 'ADHERENT.csv' INTO TABLE ADHERENT FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'AUTEUR.csv' INTO TABLE AUTEUR FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'OEUVRE.csv' INTO TABLE OEUVRE FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'EXEMPLAIRE.csv' INTO TABLE EXEMPLAIRE FIELDS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'EMPRUNT.csv' INTO TABLE EMPRUNT FIELDS TERMINATED BY ',';


-- Commande pour supprimer les warnings des dates : 
UPDATE EMPRUNT SET dateRendu = NULL WHERE CAST(dateRendu AS CHAR(10)) = '0000-00-00';
UPDATE OEUVRE SET dateParution = NULL WHERE CAST(dateParution AS CHAR(10)) = '0000-00-00';